---
title: "16S Visualization Tutorial"
output:
  html_document:
    mathjax: null
    section_divs: false
    smart: false
    highlight: null
    theme: null
    template: ./tutorial_template.html
    toc: true
  # github_document:
  #   toc: true
  #   toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, tidy=TRUE, tidy.opts = list(width.cutoff=80))
```

The visualizations are a set of html files that can be viewed in the browser.

## Plotly Graphs
- The title and axis labels can be edited by clicking on them.  
<a href="https://youtu.be/ONBAjvhWZkM" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>
- The legend can also be edited, and can be moved by clicking and dragging.  
<a href="https://youtu.be/vUjhMzbKtp8" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>
- To save the plot, click on the camera icon in the menu.  The browser will download the png file.<br />
<a href="https://youtu.be/Lbe9IaeEEyY" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>
- To edit the graph further, you can export the data to Plotly Chart Studio by clicking on "Export Data to Plotly."  See the [Plotly Chart Studio tutorials](http://help.plot.ly/tutorials/){target="_blank" rel="noopener noreferrer"} for more information.

## Heatmap
The [Morpheus documentation](https://software.broadinstitute.org/morpheus/documentation.html){target="_blank" rel="noopener noreferrer"} shows how to use the various features of the heatmap.  We will show some examples of how these features could be used specifically for the output of the Nephele 16S pipelines.  Note: the features work best in Google Chrome; you may have problems with other browsers. 

### Filter Low Abundant Taxa
Taxa can be filtered based on maximum abundance across all samples or the number of samples for which they are present.

1. Select **Tools** > **Create Calculated Annotation**.
    - Maximum abundance: Enter `Max` for **Annotation Name** and `MAX()` for **Formula**.
    - Number of samples: Enter **Annotation Name** `Num samples` and `COUNTIF(">0")` for **Formula**.
2. Click **OK**.
3. Select **Tools** > **Filter** > **Add**.
    - Maximum abundance: Choose **Field** `Max`.  You can choose a minimum value for the range.  This will filter out taxa which are below this value across all samples.  Or you can `Switch to top filter` to see the top most abundant taxa.
    - Number of samples: Choose **Field** `Num samples` .  You can choose a range for the number of samples or you can `Switch to top filter` to see the most frequent taxa across all samples.  

<a href="https://youtu.be/nnZCI_dTULw" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>


### View the heatmap at different taxonomic levels
1. Select **Tools** > **Collapse**.
2. Choose **Collapse Method** `Sum` and **Collapse** `Rows`.  
3. For **Collapse Field**, choose the `taxonomic level` at which you would like to view the heatmap.
4. Click **OK**, and a new tab will open with the heatmap at the desired level.
5. Select **View** > **Options** > **Annotations** > **Row Annotations** > `taxonomic level` > **Close**.  
This will show the new row names for the heatmap.

<a href="https://youtu.be/iQMVc7Beoc0" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>

### Sort the heatmap by taxonomic level
1. Select **View** > **Options** > **Annotations** > **Row Annotations** > `taxonomic level` > **Close**.  
This will show a column with the taxonomic level annotations for the heatmap.
2. Select **Tools** > **Sort/Group** > **Add sort level** > `taxonomic level`.  Then select **Group By** > `taxonomic level`.

<a href="https://youtu.be/iAQiUNSzMfw" target="_blank" rel="noopener noreferrer">Video<span class="glyphicon glyphicon-facetime-video video-icon"></span></a>

{% if download_url %}

### Here are some example visualization files <span><a class="glyphicon glyphicon-download-alt" href="{{ download_url }}" target="_blank" rel="noopener noreferrer"></a></span> {#example-files}

These data are from a 2018 publication in Journal of Experimental Medicine entitled "Contextual control of skin immunity and inflammation by Corynebacterium" ([https://doi.org/10.1084/jem.20171079](https://doi.org/10.1084/jem.20171079){target="_blank" rel="noopener noreferrer"}).

{% endif %}
