#!/usr/bin/env python3
## Automatically generated.  Do Not Edit.  Default parameters.  See nephele2/pipelines/DADA2/dada2nephele/R/computation.R .onLoad
NBASES='100000000'
MAXEE='5'
TRUNCQ='4'
TRUNCLEN='0'
MINOVERLAP='12'
MAXMISMATCH='0'
JUSTCONCATENATE='FALSE'
MINBOOT='80'
TRIMLEFT='0'
TRIMOVERHANG='FALSE'
OUTPUTFASTA='seq.fasta'
BIOMFILE='taxa.biom'
OTUTABLE='OTU_table.txt'
BIOMSUMMARY='otu_summary_table.txt'
REFDB='dada2_silva_v132/silva_nr_v132_train_set.fa'
REFDB_SPECIES='dada2_silva_v132/silva_species_assignment_v132.fa'
MIN_SEQ_LENGTH='75'
TAXMETHOD='rdp'
TAXTABLE='taxonomy_table.txt'
